environment:
  matrix:
  - TOXENV: py37
  pypitoken:
    secure: ysv4opRvqiJ4cKX7VBun/Kcunr+ltCylSP0z5X/+1AQqNgghRx7DHw64uxm9gXdWERToF6JtFaRIXf/Kg6F+uA46wT7WxRenjTrd/j5dsW/D/mjMaq8PTP+lHcz7tsaAM2wIO8kphvUqNcSnfkscTVKqtpm2GXEy5f0dQmDOWqf03mXPad3WhwfLsI49mjozD/3TWhZCS0MXbu8Tmt0xwRZJEKuiorTb7Bgfo2+ICI0+5OwOgCGjjEvjKUQfnsdqNrFDSzjKsz7jiL/9oimogQ==

install:
  - pip install tox
  - set PYTHONPATH=C:\projects\docs-from-tests

build_script:
  - python setup.py sdist bdist_wheel

test_script:
  - tox
  # the below is a nicety, it populates the "tests" tab of the appveyor build page,
  # it requires "--junitxml=test-output.xml" to be added to the pytest command

on_finish:
  - ps: ./tests/upload_test_results_to_appveyor.ps1

artifacts:
  - path: dist\*.*
    name: python-package

# deploy python backage for master branch builds, this runs the risk of overwriting 
# a package if the version isn't updated, which is hackily avoided with the 
# --skip-existing parameter
for:
-
  branches:
    only:
      - master
  deploy_script:
    - python -m twine upload -u __token__ -p ${pypitoken} --repository-url https://test.pypi.org/legacy/ --skip-existing dist/*

# the below means that normally only the person that broke the build gets an email, instead of everybody
notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    subject: 'Build {{status}}'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false

 