environment:
  matrix:
  - TOXENV: py37
  pypitoken:
    secure: Y9Yz4iNYJiWdoFrO7hxMyW67XB7T5fBkG47M0+wmDKUnA3rj+Z0MKjJ2d9pYEiJG7ii5MsEeLxwpppvPhFI6tJHTbMnaEXyctOmbG4+CtxTHva5CylVkhfeWHp7J2zp4x3tqms0Dg1mutRo2CZG1cf5T4HbMFDZaTmyZoS1O9Zkpwnp+W3AoR248b/PfKpf9BKIn/x5FrC7ofw1fv0EJCWm/B/O++1cV3svul48wPo6pcUbIMCTfN3omrEbgnRCv05hXuTCb16yBm3M/SJhaOXXjNjDrl2230l3JdlOtR3g=

install:
  - pip install tox
  - set PYTHONPATH=C:\projects\docs-from-tests
  - pip install --user --upgrade setuptools wheel
  - pip install --user --upgrade twine

build_script:
  - python setup.py sdist bdist_wheel

test_script:
  - tox
  # the below is a nicety, it populates the "tests" tab of the appveyor build page,
  # it requires "--junitxml=test-output.xml" to be added to the pytest command

on_finish:
  - ps: ./tests/upload_test_results_to_appveyor.ps1

artifacts:
  - path: dist\*.*
    name: python-package

# deploy python backage for master branch builds, this runs the risk of overwriting 
# a package if the version isn't updated, which is hackily avoided with the 
# --skip-existing parameter
for:
-
  branches:
    only:
      - master
  deploy_script:
    - python -m twine upload -u __token__ -p %pypitoken% --skip-existing dist/*

# the below means that normally only the person that broke the build gets an email, instead of everybody
notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    subject: 'Build {{status}}'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false

 