environment:
  matrix:
    - PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"

install:
  - set PYTHONPATH=C:\projects\res-python-project-template

build: false

test_script:
  - cmd: pytest --junitxml=test-output.xml
  # the below is a nicety, it populates the "tests" tab of the appveyor build page,
  # it requires "--junitxml=test-output.xml" to be added to the pytest command
  - ps: ./tests/upload_test_results_to_appveyor.ps1

# the below means that normally only the person that broke the build gets an email, instead of everybody
notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    subject: 'Build {{status}}'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false
